# **Session 3**
# Excercises

### List comprehension 1

Given dictionary is consisted of vehicles and their weights in kilograms. Contruct a list of the names of vehicles with weight below 5000 kilograms. In the same list comprehension make the key names all upper case.

_Hint: dict[i]  can be used to access the value of the key: i in a dictionary named dict_

In [ ]:
dict={"Sedan": 1500, "SUV": 2000, "Pickup": 2500, "Minivan": 1600, "Van": 2400, "Semi": 13600, "Bicycle": 7, "Motorcycle": 110}

#Type your answer here.

lst=[]

print(lst)

[]

In [ ]:
#solution
lst = [a.upper() for a in dict if dict[a]<5000]
lst

['SEDAN', 'SUV', 'PICKUP', 'MINIVAN', 'VAN', 'BICYCLE', 'MOTORCYCLE']

### Mountain Heights 1
Wikipedia has a list of the tallest mountains in the world, with each mountain's elevation.
https://en.wikipedia.org/wiki/List_of_mountains_by_elevation

 Pick five mountains from this list.

1. Create a dictionary with the mountain names as keys, and the elevations as values.
2. Print out just the mountains' names, by looping through the keys of your dictionary.
3. Print out just the mountains' elevations, by looping through the values of your dictionary.
4. Print out a series of statements telling how tall each mountain is: "Everest is 8848 meters tall."

Revise your output, if necessary.

- Make sure there is an introductory sentence describing the output for each loop you write.
- Make sure there is a blank line between each group of statements.

In [ ]:
#create dict
dict_mount={"Mount Everest"	:8848	,"K2":8612	,"Kangchenjunga":8586	,"Lhotse":8516,"Makalu":8485}
dict_mount

{'K2': 8612,
 'Kangchenjunga': 8586,
 'Lhotse': 8516,
 'Makalu': 8485,
 'Mount Everest': 8848}

In [ ]:
#print mountain names
for key in dict_mount.keys():
    print('Mountain name: %s' , key, "\n\n")

Mountain name: %s Mount Everest


Mountain name: %s K2


Mountain name: %s Kangchenjunga


Mountain name: %s Lhotse


Mountain name: %s Makalu

In [ ]:
#print out just elevantions
for value in dict_mount.values():
    print( value)

8848
8612
8586
8516
8485

In [ ]:
#statements
for word, meaning in dict_mount.items():
    print( word, "is", meaning, "tall")

Mount Everest is 8848 tall
K2 is 8612 tall
Kangchenjunga is 8586 tall
Lhotse is 8516 tall
Makalu is 8485 tall

### Mountain Heights 2
Revise your final output from Mountain Heights 1, so that the information is listed in alphabetical order by each mountain's name.

That is, print out a series of statements telling how tall each mountain is: "Everest is 8848 meters tall."
Make sure your output is in alphabetical order.

In [ ]:
for word, meaning in sorted(dict_mount.items()):
    print( word, "is", meaning, "tall")

K2 is 8612 tall
Kangchenjunga is 8586 tall
Lhotse is 8516 tall
Makalu is 8485 tall
Mount Everest is 8848 tall

### Functions

_Favorite Colors_<br>

1. Write a function that takes two arguments, a person's name and their favorite color. 
2. Use the input function to save the name and color
3. Then use the name variable to pass it through the function. The function should print out a statement such as "Ash's favorite color is violet." 
3. The name needs to be CAPITALIZED in the output

Call your function three times, with a different person and color each time.

In [5]:
def colors(name, color):
    print( name.upper()+"'s","favorite color is", color)

name=input("Please enter your name\t")
color=input("Please enter your favorite color\t")

colors(name,color)

Please enter your name	ash
Please enter your favorite color	red
ASH's favorite color is red

### More list comprehension

1. Find all of the numbers from 1â€“1000 that have a 6 in them
2. Count the number of spaces in a string (use string above)
3.  Find all of the words in a string that are less than 5 letters (use string above)

In [ ]:
# Use for the questions above:
nums = [i for i in range(1,1001)]
string = "Practice Problems for List Comprehension."

In [6]:
one = [num for num in nums if "6" in str(num)]

In [8]:
two = [char for char in string if char == " "]
print(two)
two = len([char for char in string if char == " "])
print(two)

[' ', ' ', ' ', ' ']
4

In [15]:
color="violet "
len(color)

7

In [13]:
words = string.split(" ")
print(words)
three = [x for x in words if (len(x) < 5)]
print(three)

['Practice', 'Problems', 'for', 'List', 'Comprehension.']
['for', 'List']

### Remove floats

Given a list of numbers, remove floats (numbers with decimals)

In [ ]:
original_list = [2,3.75,.04,59.354,6,7.7777,8,9]

In [ ]:
#solution
only_ints = [number for number in original_list if type(number) == int]
print(only_ints)

[2, 6, 8, 9]